name: 'test'
run-name: 'testing actions'
on:
  schedule:
  - cron: '15 * * * *'
  workflow_dispatch:
jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
     - run: echo 'test is being run on a ${{runner.os}} machine!'
     - run: git clone https://github.com/kevfort/suiversions.git
     - name: Check out repository code
     - uses: actions/checkout@v4
     - run: python3 test.py
  
